name: 'Ulmas & Co'
favicon: null
layout_spectrum: 0.6708624963648617
typography_spectrum: 0.5415982911363244
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7608658208046108
  lightness: 0.42359806201420724
  saturation: 0.36229503550566733
  rhythmicContrast: 0.2328440072014928
purpose: []
