name: 'Ulmas & Co'
favicon: null
layout_spectrum: 0.49754
typography_spectrum: 0.7408
title: 'Ulmas & Co'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#182042'
    - '#5f5e5a'
    - '#a5b9b9'
    - '#8f999c'
    - '#c6daea'
  brandStrength: 0.5625
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
